In [1]:
import numpy as np

In [2]:
np.set_printoptions(suppress=True) 

In [8]:
scalar=5.0
print(type(scalar))

vector=np.array([2,3,45,6,54,32,4,5])
print(vector)
print(type(vector))

matrix=np.array([[1,2,3],
                 [4,6,4],
                 [7,5,4]])
print(matrix)
print(type(matrix))

tensor=np.array([[[1,2,3],
                  [4,5,6],
                  [6,4,3]],[[2,5,3],
                            [7,5,3],
                            [5,3,2]]])
print(tensor)
tensor.shape


<class 'float'>
[ 2  3 45  6 54 32  4  5]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 6 4]
 [7 5 4]]
<class 'numpy.ndarray'>
[[[1 2 3]
  [4 5 6]
  [6 4 3]]

 [[2 5 3]
  [7 5 3]
  [5 3 2]]]


(2, 3, 3)

2 <b>Creating vectors and matrices for Ml style data

In [14]:
#imagine we have 3 sample and 2 features
x=np.array([[2,30], #sample 1
            [5,80], #sample2
            [1,30]]) #sample3  

y=np.array([0,1,0])

print("input Data matrx",x)
print(x.shape)

print("Output vector\n",y)
print("y shape",y.shape)

x_transpose=x.T
print(x_transpose)



input Data matrx [[ 2 30]
 [ 5 80]
 [ 1 30]]
(3, 2)
Output vector
 [0 1 0]
y shape (3,)
[[ 2  5  1]
 [30 80 30]]


In [ ]:
v1=np.array([2,4,5])
v2=np.array([3,5,3])
v_add=v1+v2
print("addition of two number:",v_add)

v1_scaled=2*v1
print(v1_scaled)



addition of two number: [5 9 8]
[ 4  8 10]


In [16]:
np.set_printoptions(suppress=True)

In [17]:
v1=np.array([1,3])
v2=np.array([4,2])

print("v1:",v1)
print("\nv2:",v2)

v1: [1 3]

v2: [4 2]


In [18]:
dot=np.dot(v1,v2)
print("dot producct v1.v2:",dot)


dot producct v1.v2: 10


<i>Eculdian Distance

In [19]:
diff=v1-v2
print("difference of v1 and v2:",diff)

difference of v1 and v2: [-3  1]


In [20]:
distance=np.linalg.norm(diff)
print("Ecludian distance:",distance) 

Ecludian distance: 3.1622776601683795


<b>Matrix multiplication and Linear Model

In [21]:
w=np.array([[8,5],
            [8,1]])
x=np.array([[4,5],
            [3,4]])

xw=x@w
print(xw)

[[72 25]
 [56 19]]


<b>y=xw+b

In [22]:
b=2.0
print(b)


2.0


In [23]:
y=xw+b
print( y)

[[74. 27.]
 [58. 21.]]


In [24]:
data = np.array([[85, 26.6, 31, 0],
                 [183, 23.3, 32, 1],
                 [89, 20.1, 21, 0],
                 [137, 43.1, 33, 1],])

print("full data matrix:",data)
print("Data shape",data.shape)




full data matrix: [[ 85.   26.6  31.    0. ]
 [183.   23.3  32.    1. ]
 [ 89.   20.1  21.    0. ]
 [137.   43.1  33.    1. ]]
Data shape (4, 4)


In [28]:
x_feautres=data[:,:-1]
y_target=data[:,-1]

print("\nFeatures matrix x:\n ",x_feautres)
print("X_shape:",x.shape)

print("\nTarget vector y:",y_target)
print("y_shape",y_target.shape)


Features matrix x:
  [[ 85.   26.6  31. ]
 [183.   23.3  32. ]
 [ 89.   20.1  21. ]
 [137.   43.1  33. ]]
X_shape: (2, 2)

Target vector y: [0. 1. 0. 1.]
y_shape (4,)
