In [1]:
%pip install numpy pandas matplotlib scikit-learn -q

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


from sklearn.model_selection import train_test_split,KFold
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    
    roc_auc_score,
    roc_curve
)


pd.set_option("display.max_columns",None)
sns.set_style("whitegrid")

In [3]:
df=pd.read_csv(r"C:\Users\kaush\Desktop\SummerBreak\Machine Learning\MachineLearning\Data preprocessing\Handling_imbalanced\diabetes.csv")

In [4]:
df.shape

(768, 9)

In [5]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1


In [25]:
df["Outcome"].value_counts(
    
)

Outcome
0    500
1    268
Name: count, dtype: int64

In [26]:
x=df.drop(columns=["Outcome"])
y=df["Outcome"]

5 . K fold setup

In [27]:
kf=KFold(n_splits=5,shuffle=True,random_state=42)

6 Loop through the folds

In [32]:
for fold,(train_idx,test_idx) in enumerate(kf.split(x),start=1):
    print(fold)
    print(len(train_idx))
    print((train_idx[:5]))
    
    print(len(test_idx))
    print((test_idx[:5]))
    
    print ("-"*50)
    

1
614
[0 1 3 4 5]
154
[ 2  7 10 23 30]
--------------------------------------------------
2
614
[0 1 2 3 4]
154
[ 6 11 15 18 24]
--------------------------------------------------
3
614
[1 2 3 4 5]
154
[ 0  9 12 17 19]
--------------------------------------------------
4
615
[0 1 2 4 6]
153
[ 3  5  8 16 26]
--------------------------------------------------
5
615
[0 2 3 5 6]
153
[ 1  4 13 14 20]
--------------------------------------------------


In [48]:
accuracy_list=[]
precision_list=[]
recall_list=[]
f1_list=[]
roc_auc_list=[]

In [49]:
for fold, (train_idx,test_idx) in enumerate(kf.split(x),start=1):
    #split data
    
    X_train,X_test=x.iloc[train_idx],x.iloc[test_idx]
    y_train,y_test=y.iloc[train_idx],y.iloc[test_idx]
    
    scaler=StandardScaler()
    X_train_scaled=scaler.fit_transform(X_train)
    X_test_scaled=scaler.transform(X_test)
    
    #training the modell
    model=LogisticRegression()
    
    model.fit(X_train_scaled,y_train)
    
    #getting the inference
    
    y_pred=model.predict(X_test_scaled) 
    y_prob=model.predict_proba(X_test_scaled)
    
    #evalutation metrics
    acc=accuracy_score(y_test,y_pred)
    prec=precision_score(y_test,y_pred)
    rec=recall_score(y_test,y_pred)
    f1=f1_score(y_test,y_pred)
    auc=roc_auc_score(y_test,y_pred)    
    
    #store matrix
    accuracy_list.append(acc)
    precision_list.append(prec)
    recall_list.append(rec)
    f1_list.append(f1)
    roc_auc_list.append(auc)
    
    
    #print fold result
    
    print(f" fold : {fold}")
    print(f"  Accuracy : {acc:.3f}")
    print(f"  precision : {prec:.3f}")
    print(f"  Recall : {rec:.3f}")
    print(f"  f1_score : {f1:.3f}")
    
    print(f"  rec_auc : {auc:.3f}")
    print("-"*50)

    
    
    
    
    

 fold : 1
  Accuracy : 0.753
  precision : 0.649
  Recall : 0.673
  f1_score : 0.661
  rec_auc : 0.735
--------------------------------------------------
 fold : 2
  Accuracy : 0.786
  precision : 0.659
  Recall : 0.617
  f1_score : 0.637
  rec_auc : 0.738
--------------------------------------------------
 fold : 3
  Accuracy : 0.753
  precision : 0.780
  Recall : 0.525
  f1_score : 0.627
  rec_auc : 0.714
--------------------------------------------------
 fold : 4
  Accuracy : 0.804
  precision : 0.758
  Recall : 0.532
  f1_score : 0.625
  rec_auc : 0.728
--------------------------------------------------
 fold : 5
  Accuracy : 0.745
  precision : 0.732
  Recall : 0.517
  f1_score : 0.606
  rec_auc : 0.701
--------------------------------------------------


In [52]:
print(precision_list)
print(accuracy_list)


[0.6491228070175439, 0.6590909090909091, 0.7804878048780488, 0.7575757575757576, 0.7317073170731707]
[0.7532467532467533, 0.7857142857142857, 0.7532467532467533, 0.803921568627451, 0.7450980392156863]


In [51]:
np.mean(accuracy_list)

np.float64(0.7682454800101859)

In [57]:
mean_accuracy=round(np.mean(accuracy_list)*100,3)
mean_precision=round(np.mean(precision_list)*100,3)
mean_recall=round(np.mean(recall_list)*100,3)
mean_f1=round(np.mean(f1_list)*100,3)
mean_roc_auc=round(np.mean(roc_auc_list)*100,3)



In [58]:
print("Kfold cross validation:")
print(f"Mean Accuracy: {mean_accuracy}")
print(f"Mean precision: {mean_precision}")
print(f"Mean recall: {mean_recall}")
print(f"Mean f1: {mean_f1}")
print(f"Mean roc_auc: {mean_roc_auc}")


Kfold cross validation:
Mean Accuracy: 76.825
Mean precision: 71.56
Mean recall: 57.27
Mean f1: 63.132
Mean roc_auc: 72.333
