Installing & import Numpy Library

In [1]:
%pip install numpy


  Using cached numpy-2.4.6-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Using cached numpy-2.4.6-cp313-cp313-win_amd64.whl (12.3 MB)
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
print(np.__version__
      )

2.4.6


***compare python list and numpy***

In [7]:
import time
import numpy as np
n=100_000
py_list=list(range(n))
np_array=np.arange(n)
print(len(py_list))
print(len(np_array))

print(py_list[0:5])
print(np_array[0:5])
t1=time.time()
py_result=[x*2 for x in py_list]
t2=time.time()

t3=time.time()
np_result=[x*2 for x in np_array]
t4=time.time()

print("list timee:",t2-t1)
print("np time:",t4-t3)

100000
100000
[0, 1, 2, 3, 4]
[0 1 2 3 4]
list timee: 0.003809213638305664
np time: 0.01154637336730957


In [ ]:
t1=time.time()
py_result=[x*2 for x in py_list]
t2=time.time()

t3=time.time()
np_result=[x*2 for x in np_array]
t4=time.time()

print("list timee:",t2-t1)
print("np time:",t4-t3)

**creating numpy array***

In [3]:
arr1=np.array([1,2,3,4,5,6,7,8])
print(arr1)

[1 2 3 4 5 6 7 8]


In [5]:
arr2=np.array([[1,2,3],[3,4,5],[4,6,4]])
print(arr2)

[[1 2 3]
 [3 4 5]
 [4 6 4]]


In [7]:
zero=np.zeros((3,4))
print (zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
one=np.ones((3,4))
print(one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
random=np.random.rand(3,4)
print(random)   

[[0.80955675 0.25006893 0.27269057 0.47511138]
 [0.61820617 0.21623323 0.80469412 0.18161884]
 [0.13528957 0.39242363 0.82655661 0.09153065]]


In [12]:
eye=np.eye(4)
print(eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


***Array Operation***

In [20]:
a=np.array([1,2,3])
b=np.array([4,5,6])

print("Addition of ",a+b)
print("subtraction of ",a-b)
print("Multiplication of ",a*b)
print("subtraction of ",a/b)
print("Dot prodiunt",np.dot(a,b))
print("Cross product",np.cross(a,b))




Addition of  [5 7 9]
subtraction of  [-3 -3 -3]
Multiplication of  [ 4 10 18]
subtraction of  [0.25 0.4  0.5 ]
Dot prodiunt 32
Cross product [-3  6 -3]


**reshaping and flatting**


In [31]:
arr =np.arange(1,10)
print(arr)
reshaped=arr.reshape(3,3)
print(reshaped)
flatten=reshaped.flatten()
print(flatten)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
