In [1]:
%pip install plotly

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np
import pandas as pd
 
np.random.seed(23)
mu_vec1=np.array([0,0,0])
cov_mat1=np.array([[1,0,0],[0,1,0],[0,0,1]])
 
class1_sample=np.random.multivariate_normal(mu_vec1,cov_mat1,20)
 
df=pd.DataFrame(class1_sample,columns=["feature1","feature2","feature3"])
df['target']=1


mu_vec2=np.array([1,1,1])
cov_mat2=np.array([[1,0,0],[0,1,0],[0,0,1]])
 
class2_sample=np.random.multivariate_normal(mu_vec2,cov_mat2,20)
 
df1=pd.DataFrame(class1_sample,columns=["feature1","feature2","feature3"])
df1['target']=0

# df=df.a(df1,ignore_index=True)
df=pd.concat([df,df1],ignore_index=True)
 
df=df.sample(40)

In [3]:
df

,feature1,feature2,feature3,target
2,-0.367548,-1.137460,-1.322148,1
34,0.420623,0.411620,-0.071324,0
14,0.420623,0.411620,-0.071324,1
11,1.968435,-0.547788,-0.679418,1
12,-2.506230,0.146960,0.606195,1
29,1.267248,0.173634,-1.223255,0
31,1.968435,-0.547788,-0.679418,0
4,0.322272,0.060343,-1.043450,1
32,-2.506230,0.146960,0.606195,0
33,-0.022539,0.013422,0.935945,0


In [5]:
import plotly.express as px
fig=px.scatter_3d(df,x=df['feature1'],y=df['feature2'],z=df['feature3'],color=df['target'].astype('str'))
fig.update_traces(marker=dict(size=12,line=dict(width=2,color="DarkSlateGrey")),selector=dict(mode='marker'))
fig.show()

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

In [7]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
df.iloc[:,0:3]=scaler.fit_transform(df.iloc[:,0:3])

In [13]:
covariance_matrix=np.cov([df.iloc[:,0],df.iloc[:,1],df.iloc[:,2]])
print('covariance_matrix'  , covariance_matrix,"\n")

covariance_matrix [[ 1.02564103  0.19874576 -0.28147286]
 [ 0.19874576  1.02564103  0.10675198]
 [-0.28147286  0.10675198  1.02564103]] 



In [15]:
#find out the eigen values and eigen vectors
eigen_value,eigen_vectors=np.linalg.eig(covariance_matrix)

In [16]:
eigen_value

array([0.6256614 , 1.32630385, 1.12495783])

In [17]:
eigen_vectors

array([[-0.65172443,  0.74834128,  0.12345283],
       [ 0.48046517,  0.28140349,  0.8306415 ],
       [-0.58686326, -0.60066414,  0.54294945]])

In [18]:
pc=eigen_vectors[0:2]
pc

array([[-0.65172443,  0.74834128,  0.12345283],
       [ 0.48046517,  0.28140349,  0.8306415 ]])

In [20]:
transformed_df=np.dot(df.iloc[:,0:3],pc.T)
new_df=pd.DataFrame(transformed_df,columns=["pc1","pc2"])
new_df['target']=df['target'].values
new_df

,pc1,pc2,target
0,-1.078773,-2.044435,1
1,0.376154,0.249784,0
2,0.376154,0.249784,1
3,-1.682116,-0.124367,1
4,1.888923,-0.404657,1
5,-0.559160,-0.693634,0
6,-1.682116,-0.124367,0
7,-0.107685,-0.957342,1
8,1.888923,-0.404657,0
9,0.348857,0.949148,0
